const authors = ["Wybierz autora...",
  "Albert Camus",
  "Albert Einstein",
  "Andrzej Sapkowski",
  "Anonim",
  "Antoine de Saint-Exupéry",
  "Arthur Schopenhauer",
  "Bertrand Russell",
  "Cyceron",
  "Emil Zola",
  "Erich Fromm",
  "Eurypides",
  "Fiodor Dostojewski",
  "Francisco Goya",
  "Fryderyk Engels",
  "George Orwell",
  "Hannah Arendt",
  "Henry Ford",
  "Horacy",
  "Immanuel Kant",
  "J.R.R. Tolkien",
  "Jan Twardowski",
  "Józef Stalin",
  "Julian Tuwim",
  "Karol Marks",
  "Leonardo da Vinci",
  "Lew Tołstoj",
  "Mahatma Gandhi",
  "Margaret Thatcher",
  "Mikołaj Rej",
  "Monteskiusz",
  "Napoleon Bonaparte",
  "Nelson Mandela",
  "Oscar Wilde",
  "Owidiusz",
  "Paulo Coelho",
  "Ryszard Kapuściński",
  "Stanisław Lem",
  "Stephen King",
  "Steve Jobs",
  "Terry Pratchett",
  "William Szekspir",
  "Wisława Szymborska",
  "Wolter"
];
export { authors };
